### ISSUE TITLE
Can't boot on Ventana board

### ISSUE THREAD

**Issue by natcl** [Gateworks/ubuntu-rootfs#2]
Hello, I tried both generating my own image from this script and the pre-built one (focal-ventana.img)
Tried burning it to a microSD card but can't seem to get the Ventana to boot.
I have another image based on an older kernel (ubuntu 16) that boots fine.
Any help would be appreciated.
Thanks !

**Comment by Gateworks** [comment]
Nathanaël,

Most Ventana boards have an on-board NAND FLASH that they boot from based
on one-time-programmable fuses thus to boot from microSD you actually
have to boot the bootloader from NAND first and have it load/boot your OS
from microSD via U-Boot configuration.

Please send an e-mail to support@gateworks.com letting them know the board
model you have (or serial number from the bar-code on the board as that
will tell us) and what you are having trouble with. If the board is not
booting from the NAND FLASH then it is likely that somehow you have
corrupted the software image there and need to use the Gateworks JTAG
dongle to re-program the card. Please provide as much detail as possible
and describe exactly what you mean by 'can't seem to get the Ventana to
boot' so they can answer your question in the best way possible.

Best regards,

Tim

**Comment by natcl** [comment]
Thanks, I will first go fetch the JTAG dongle at work so I can troubleshoot a bit more !
